name: Deploy web app on Github Pages

on:
  push:
    branches: [main]

jobs:
  deploy_react_app:
    runs-on: ubuntu-latest
    name: Deploy React App
    steps:
      - uses: actions/checkout@v2
      - uses: gurleensethi/react-github-pages@v0.4
        with:
          access_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
